name: CI/CD для Python

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск тестов
      run: |
        python -m unittest discover

